version: '3'
services:
  web:
    container_name: dugoutCron
    build: .
    ports:
     - "5555:80"
    volumes:
     - .:/app/src
    restart: always

networks:
  default:
    external:
      name: dugout-net