version: '3'
services:
  web:
    container_name: dugoutCron
    build: .
    ports:
     - "5040:80"
    volumes:
     - .:/app/src
    restart: always
    environment:
      TZ: "America/Winnipeg"

networks:
  default:
    external:
      name: dugout-net